version: "3.8"

services:
  spark-master:
    image: hanvocado/spark:3.2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    env_file:
      - ./.env
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark/scripts:/opt/work/spark-scripts
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 0.5G

  spark-worker:
    image: hanvocado/spark:3.2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    env_file:
      - ./.env
    depends_on:
      - spark-master
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 0.5G

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  postgres-metastore:
    image: postgres:latest
    container_name: postgres-metastore
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive"]
      interval: 10s
      timeout: 5s
      retries: 5

  hive-metastore:
    image: hanvocado/hive-metastore:4.0
    container_name: hive-metastore
    depends_on:
      postgres-metastore:
        condition: service_healthy
    environment:
      - SERVICE_NAME=metastore
      - HIVE_METASTORE_DB_TYPE=postgres
      - HIVE_METASTORE_DB_HOST=postgres-metastore
      - HIVE_METASTORE_DB_NAME=metastore
      - HIVE_METASTORE_DB_USER=hive
      - HIVE_METASTORE_DB_PASS=hive
    ports:
      - "9083:9083"
    command: >
      bash -c "
        /opt/hive/bin/schematool -initSchema -dbType postgres --verbose &&
        hive --service metastore
      "

  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047 # Web UI
      - 31010:31010
      - 32010:32010
    volumes:
      - dremio-data:/opt/dremio/data
    container_name: dremio

  airflow:
    build: ./docker/airflow
    restart: always
    container_name: airflow
    depends_on:
      - postgres-airflow
    volumes:
      - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8081:8080"
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://admin:admin@postgres-airflow:5432/airflow_db"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - ./.env
    entrypoint: /opt/airflow/start-airflow.sh

  postgres-airflow:
    image: postgres:13
    container_name: postgres-airflow
    volumes:
      - postgres-airflow:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "airflow_db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 30s
      timeout: 10s
      retries: 5

  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NB_UID=1000
      - NB_GID=100
    command: start-notebook.sh --NotebookApp.token=''
    restart: unless-stopped
    depends_on:
      - spark-master

volumes:
  minio-data:
  postgres-data:
  dremio-data:
  postgres-airflow:
